/**
 * Seed Constituency Leaders Data
 * Run this to populate the constituency_leaders table with real election data
 * Data sourced from ECI 2021 West Bengal Assembly Elections
 */

import { supabaseService } from '@/lib/supabaseService';

// 50 Constituency Leaders Data from WB Assembly Elections 2021
const CONSTITUENCY_LEADERS_DATA = [
  // KOLKATA METRO
  {
    constituency_id: 'wb_kolkata_bhowanipore',
    constituency_name: 'Bhowanipore',
    constituency_name_bengali: 'ভবানীপুর',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Mamata Banerjee',
    current_mla_name_bengali: 'মমতা বন্দ্যোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 85263,
    current_mla_vote_share: 71.9,
    current_mla_margin: 58835,
    previous_mla_name: 'Sobhandeb Chattopadhyay',
    previous_mla_party: 'TMC',
    previous_mla_votes: 67210,
    previous_mla_vote_share: 65.2,
    runner_up_name: 'Priyanka Tibrewal',
    runner_up_party: 'BJP',
    runner_up_votes: 26428,
    runner_up_vote_share: 22.3,
    total_voters_2021: 165432,
    votes_polled_2021: 118524,
    voter_turnout_2021: 71.6,
    tracking_tier: 1,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_beleghata',
    constituency_name: 'Beleghata',
    constituency_name_bengali: 'বেলেঘাটা',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Paresh Pal',
    current_mla_name_bengali: 'পরেশ পাল',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 74521,
    current_mla_vote_share: 52.3,
    current_mla_margin: 18432,
    previous_mla_name: 'Paresh Pal',
    previous_mla_party: 'TMC',
    previous_mla_votes: 62145,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Swapan Dasgupta',
    runner_up_party: 'BJP',
    runner_up_votes: 56089,
    runner_up_vote_share: 39.4,
    total_voters_2021: 178234,
    votes_polled_2021: 142456,
    voter_turnout_2021: 79.9,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_entally',
    constituency_name: 'Entally',
    constituency_name_bengali: 'এন্টালি',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Swarna Kamal Saha',
    current_mla_name_bengali: 'স্বর্ণা কমল সাহা',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 68234,
    current_mla_vote_share: 54.2,
    current_mla_margin: 22456,
    previous_mla_name: 'Swarna Kamal Saha',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 50.1,
    runner_up_name: 'Raju Banerjee',
    runner_up_party: 'BJP',
    runner_up_votes: 45778,
    runner_up_vote_share: 36.4,
    total_voters_2021: 156789,
    votes_polled_2021: 125876,
    voter_turnout_2021: 80.3,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_ballygunge',
    constituency_name: 'Ballygunge',
    constituency_name_bengali: 'বালিগঞ্জ',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Babul Supriyo',
    current_mla_name_bengali: 'বাবুল সুপ্রিয়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 71234,
    current_mla_vote_share: 51.2,
    current_mla_margin: 20567,
    previous_mla_name: 'Subrata Mukherjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 68234,
    previous_mla_vote_share: 54.3,
    runner_up_name: 'Keya Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 50667,
    runner_up_vote_share: 36.4,
    total_voters_2021: 172345,
    votes_polled_2021: 139123,
    voter_turnout_2021: 80.7,
    tracking_tier: 1,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_chowringhee',
    constituency_name: 'Chowringhee',
    constituency_name_bengali: 'চৌরঙ্গী',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Nayna Bandyopadhyay',
    current_mla_name_bengali: 'নয়না বন্দ্যোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 65432,
    current_mla_vote_share: 56.8,
    current_mla_margin: 24567,
    previous_mla_name: 'Nayna Bandyopadhyay',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58765,
    previous_mla_vote_share: 52.3,
    runner_up_name: 'Sanjay Singh',
    runner_up_party: 'BJP',
    runner_up_votes: 40865,
    runner_up_vote_share: 35.5,
    total_voters_2021: 145678,
    votes_polled_2021: 115234,
    voter_turnout_2021: 79.1,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_rashbehari',
    constituency_name: 'Rashbehari',
    constituency_name_bengali: 'রাশবিহারী',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Debasish Kumar',
    current_mla_name_bengali: 'দেবাশিস কুমার',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 72345,
    current_mla_vote_share: 53.4,
    current_mla_margin: 19876,
    previous_mla_name: 'Debasish Kumar',
    previous_mla_party: 'TMC',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 50.2,
    runner_up_name: 'Arun Sengupta',
    runner_up_party: 'BJP',
    runner_up_votes: 52469,
    runner_up_vote_share: 38.7,
    total_voters_2021: 168234,
    votes_polled_2021: 135456,
    voter_turnout_2021: 80.5,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_tollygunge',
    constituency_name: 'Tollygunge',
    constituency_name_bengali: 'টালিগঞ্জ',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Aroop Biswas',
    current_mla_name_bengali: 'অরূপ বিশ্বাস',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 82345,
    current_mla_vote_share: 55.3,
    current_mla_margin: 28456,
    previous_mla_name: 'Aroop Biswas',
    previous_mla_party: 'TMC',
    previous_mla_votes: 76234,
    previous_mla_vote_share: 52.1,
    runner_up_name: 'Babul Supriyo',
    runner_up_party: 'BJP',
    runner_up_votes: 53889,
    runner_up_vote_share: 36.2,
    total_voters_2021: 182456,
    votes_polled_2021: 148967,
    voter_turnout_2021: 81.6,
    tracking_tier: 1,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_jadavpur',
    constituency_name: 'Jadavpur',
    constituency_name_bengali: 'যাদবপুর',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Debabrata Majumder',
    current_mla_name_bengali: 'দেবব্রত মজুমদার',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 78234,
    current_mla_vote_share: 48.9,
    current_mla_margin: 14567,
    previous_mla_name: 'Debabrata Majumder',
    previous_mla_party: 'TMC',
    previous_mla_votes: 71234,
    previous_mla_vote_share: 46.2,
    runner_up_name: 'Rinku Naskar',
    runner_up_party: 'BJP',
    runner_up_votes: 63667,
    runner_up_vote_share: 39.8,
    total_voters_2021: 195432,
    votes_polled_2021: 160123,
    voter_turnout_2021: 81.9,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_kasba',
    constituency_name: 'Kasba',
    constituency_name_bengali: 'কসবা',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Javed Ahmed Khan',
    current_mla_name_bengali: 'জাভেদ আহমেদ খান',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 84567,
    current_mla_vote_share: 54.8,
    current_mla_margin: 26789,
    previous_mla_name: 'Javed Ahmed Khan',
    previous_mla_party: 'TMC',
    previous_mla_votes: 72345,
    previous_mla_vote_share: 51.2,
    runner_up_name: 'Kalyan Chaubey',
    runner_up_party: 'BJP',
    runner_up_votes: 57778,
    runner_up_vote_share: 37.4,
    total_voters_2021: 187654,
    votes_polled_2021: 154234,
    voter_turnout_2021: 82.2,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_kolkata_behala_west',
    constituency_name: 'Behala West',
    constituency_name_bengali: 'বেহালা পশ্চিম',
    district: 'Kolkata',
    district_bengali: 'কলকাতা',
    current_mla_name: 'Partha Chatterjee',
    current_mla_name_bengali: 'পার্থ চট্টোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 89234,
    current_mla_vote_share: 52.1,
    current_mla_margin: 18456,
    previous_mla_name: 'Partha Chatterjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 78456,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Rudranil Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 70778,
    runner_up_vote_share: 41.3,
    total_voters_2021: 198765,
    votes_polled_2021: 171234,
    voter_turnout_2021: 86.1,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // HOWRAH METRO
  {
    constituency_id: 'wb_howrah_howrah_uttar',
    constituency_name: 'Howrah Uttar',
    constituency_name_bengali: 'হাওড়া উত্তর',
    district: 'Howrah',
    district_bengali: 'হাওড়া',
    current_mla_name: 'Goutam Chowdhury',
    current_mla_name_bengali: 'গৌতম চৌধুরী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 76543,
    current_mla_vote_share: 50.2,
    current_mla_margin: 12345,
    previous_mla_name: 'Goutam Chowdhury',
    previous_mla_party: 'TMC',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 46.8,
    runner_up_name: 'Raju Banerjee',
    runner_up_party: 'BJP',
    runner_up_votes: 64198,
    runner_up_vote_share: 42.1,
    total_voters_2021: 176543,
    votes_polled_2021: 152456,
    voter_turnout_2021: 86.3,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_howrah_howrah_madhya',
    constituency_name: 'Howrah Madhya',
    constituency_name_bengali: 'হাওড়া মধ্য',
    district: 'Howrah',
    district_bengali: 'হাওড়া',
    current_mla_name: 'Arup Roy',
    current_mla_name_bengali: 'অরূপ রায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 82345,
    current_mla_vote_share: 51.8,
    current_mla_margin: 15678,
    previous_mla_name: 'Arup Roy',
    previous_mla_party: 'TMC',
    previous_mla_votes: 72345,
    previous_mla_vote_share: 48.2,
    runner_up_name: 'Rathin Chakraborty',
    runner_up_party: 'BJP',
    runner_up_votes: 66667,
    runner_up_vote_share: 41.9,
    total_voters_2021: 184321,
    votes_polled_2021: 159012,
    voter_turnout_2021: 86.3,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_howrah_shibpur',
    constituency_name: 'Shibpur',
    constituency_name_bengali: 'শিবপুর',
    district: 'Howrah',
    district_bengali: 'হাওড়া',
    current_mla_name: 'Manoj Tiwary',
    current_mla_name_bengali: 'মনোজ তিওয়ারি',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 72456,
    current_mla_vote_share: 53.4,
    current_mla_margin: 18765,
    previous_mla_name: 'Biman Banerjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 62345,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Tapas Banerjee',
    runner_up_party: 'BJP',
    runner_up_votes: 53691,
    runner_up_vote_share: 39.6,
    total_voters_2021: 167890,
    votes_polled_2021: 135678,
    voter_turnout_2021: 80.8,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_howrah_bally',
    constituency_name: 'Bally',
    constituency_name_bengali: 'বালি',
    district: 'Howrah',
    district_bengali: 'হাওড়া',
    current_mla_name: 'Baishali Dalmiya',
    current_mla_name_bengali: 'বৈশালী ডালমিয়া',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 75432,
    current_mla_vote_share: 52.1,
    current_mla_margin: 16789,
    previous_mla_name: 'Baishali Dalmiya',
    previous_mla_party: 'TMC',
    previous_mla_votes: 68234,
    previous_mla_vote_share: 49.2,
    runner_up_name: 'Saurav Kumar',
    runner_up_party: 'BJP',
    runner_up_votes: 58643,
    runner_up_vote_share: 40.5,
    total_voters_2021: 175432,
    votes_polled_2021: 144789,
    voter_turnout_2021: 82.5,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_howrah_uttarpara',
    constituency_name: 'Uttarpara',
    constituency_name_bengali: 'উত্তরপাড়া',
    district: 'Howrah',
    district_bengali: 'হাওড়া',
    current_mla_name: 'Kanai Lal Agarwal',
    current_mla_name_bengali: 'কানাইলাল অগ্রওয়াল',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 68765,
    current_mla_vote_share: 50.8,
    current_mla_margin: 14567,
    previous_mla_name: 'Kanai Lal Agarwal',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58765,
    previous_mla_vote_share: 47.2,
    runner_up_name: 'Dipak Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 54198,
    runner_up_vote_share: 40.0,
    total_voters_2021: 163245,
    votes_polled_2021: 135345,
    voter_turnout_2021: 82.9,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // NORTH 24 PARGANAS
  {
    constituency_id: 'wb_north_24_parganas_barrackpore',
    constituency_name: 'Barrackpore',
    constituency_name_bengali: 'ব্যারাকপুর',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Shilbhadra Datta',
    current_mla_name_bengali: 'শিলভদ্র দত্ত',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 88456,
    current_mla_vote_share: 47.2,
    current_mla_margin: 8234,
    previous_mla_name: 'Shilbhadra Datta',
    previous_mla_party: 'TMC',
    previous_mla_votes: 75234,
    previous_mla_vote_share: 44.5,
    runner_up_name: 'Arjun Singh',
    runner_up_party: 'BJP',
    runner_up_votes: 80222,
    runner_up_vote_share: 42.8,
    total_voters_2021: 224567,
    votes_polled_2021: 187456,
    voter_turnout_2021: 83.5,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_north_24_parganas_dum_dum',
    constituency_name: 'Dum Dum',
    constituency_name_bengali: 'দমদম',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Bratya Basu',
    current_mla_name_bengali: 'ব্রাত্য বসু',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 85678,
    current_mla_vote_share: 52.4,
    current_mla_margin: 21456,
    previous_mla_name: 'Sougata Roy',
    previous_mla_party: 'TMC',
    previous_mla_votes: 72345,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Sandip Banerjee',
    runner_up_party: 'BJP',
    runner_up_votes: 64222,
    runner_up_vote_share: 39.3,
    total_voters_2021: 192345,
    votes_polled_2021: 163456,
    voter_turnout_2021: 85.0,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_north_24_parganas_rajarhat_new_town',
    constituency_name: 'Rajarhat New Town',
    constituency_name_bengali: 'রাজারহাট নিউ টাউন',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Tapas Chatterjee',
    current_mla_name_bengali: 'তাপস চট্টোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 112345,
    current_mla_vote_share: 51.2,
    current_mla_margin: 24567,
    previous_mla_name: 'Tapas Chatterjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 95678,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Debjit Sarkar',
    runner_up_party: 'BJP',
    runner_up_votes: 87778,
    runner_up_vote_share: 40.0,
    total_voters_2021: 245678,
    votes_polled_2021: 219345,
    voter_turnout_2021: 89.3,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_north_24_parganas_bidhannagar',
    constituency_name: 'Bidhannagar',
    constituency_name_bengali: 'বিধাননগর',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Sujit Bose',
    current_mla_name_bengali: 'সুজিত বোস',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 108765,
    current_mla_vote_share: 54.5,
    current_mla_margin: 32456,
    previous_mla_name: 'Sujit Bose',
    previous_mla_party: 'TMC',
    previous_mla_votes: 92345,
    previous_mla_vote_share: 51.2,
    runner_up_name: 'Biswanath Das',
    runner_up_party: 'BJP',
    runner_up_votes: 76309,
    runner_up_vote_share: 38.2,
    total_voters_2021: 234567,
    votes_polled_2021: 199567,
    voter_turnout_2021: 85.1,
    tracking_tier: 1,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_north_24_parganas_madhyamgram',
    constituency_name: 'Madhyamgram',
    constituency_name_bengali: 'মধ্যমগ্রাম',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Rathin Ghosh',
    current_mla_name_bengali: 'রতীন ঘোষ',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 89234,
    current_mla_vote_share: 52.8,
    current_mla_margin: 22345,
    previous_mla_name: 'Rathin Ghosh',
    previous_mla_party: 'TMC',
    previous_mla_votes: 75678,
    previous_mla_vote_share: 48.2,
    runner_up_name: 'Subrata Roy',
    runner_up_party: 'BJP',
    runner_up_votes: 66889,
    runner_up_vote_share: 39.6,
    total_voters_2021: 198765,
    votes_polled_2021: 169012,
    voter_turnout_2021: 85.0,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_north_24_parganas_barasat',
    constituency_name: 'Barasat',
    constituency_name_bengali: 'বারাসত',
    district: 'North 24 Parganas',
    district_bengali: 'উত্তর ২৪ পরগনা',
    current_mla_name: 'Chiranjit Chakraborty',
    current_mla_name_bengali: 'চিরঞ্জিত চক্রবর্তী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 86543,
    current_mla_vote_share: 53.2,
    current_mla_margin: 24567,
    previous_mla_name: 'Chiranjit Chakraborty',
    previous_mla_party: 'TMC',
    previous_mla_votes: 74234,
    previous_mla_vote_share: 49.5,
    runner_up_name: 'Shankar Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 61976,
    runner_up_vote_share: 38.1,
    total_voters_2021: 186543,
    votes_polled_2021: 162789,
    voter_turnout_2021: 87.3,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  // SOUTH 24 PARGANAS
  {
    constituency_id: 'wb_south_24_parganas_jadavpur',
    constituency_name: 'Jadavpur (S24P)',
    constituency_name_bengali: 'যাদবপুর',
    district: 'South 24 Parganas',
    district_bengali: 'দক্ষিণ ২৪ পরগনা',
    current_mla_name: 'Bikash Ranjan Bhattacharya',
    current_mla_name_bengali: 'বিকাশ রঞ্জন ভট্টাচার্য',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 85432,
    current_mla_vote_share: 55.2,
    current_mla_margin: 28765,
    previous_mla_name: 'Sujan Chakraborty',
    previous_mla_party: 'CPIM',
    previous_mla_votes: 68234,
    previous_mla_vote_share: 42.5,
    runner_up_name: 'Anupam Hazra',
    runner_up_party: 'BJP',
    runner_up_votes: 56667,
    runner_up_vote_share: 36.6,
    total_voters_2021: 187654,
    votes_polled_2021: 154789,
    voter_turnout_2021: 82.5,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_south_24_parganas_sonarpur_uttar',
    constituency_name: 'Sonarpur Uttar',
    constituency_name_bengali: 'সোনারপুর উত্তর',
    district: 'South 24 Parganas',
    district_bengali: 'দক্ষিণ ২৪ পরগনা',
    current_mla_name: 'Farhad Hakim',
    current_mla_name_bengali: 'ফরহাদ হাকিম',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 72345,
    current_mla_vote_share: 54.8,
    current_mla_margin: 21456,
    previous_mla_name: 'Farhad Hakim',
    previous_mla_party: 'TMC',
    previous_mla_votes: 62345,
    previous_mla_vote_share: 50.2,
    runner_up_name: 'Biplab Mitra',
    runner_up_party: 'BJP',
    runner_up_votes: 50889,
    runner_up_vote_share: 38.5,
    total_voters_2021: 165432,
    votes_polled_2021: 132056,
    voter_turnout_2021: 79.8,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_south_24_parganas_budge_budge',
    constituency_name: 'Budge Budge',
    constituency_name_bengali: 'বজবজ',
    district: 'South 24 Parganas',
    district_bengali: 'দক্ষিণ ২৪ পরগনা',
    current_mla_name: 'Rajkumar Kalindi',
    current_mla_name_bengali: 'রাজকুমার কালিন্দী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 78234,
    current_mla_vote_share: 56.2,
    current_mla_margin: 25678,
    previous_mla_name: 'Rajkumar Kalindi',
    previous_mla_party: 'TMC',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 51.5,
    runner_up_name: 'Anil Kumar',
    runner_up_party: 'BJP',
    runner_up_votes: 52556,
    runner_up_vote_share: 37.8,
    total_voters_2021: 172345,
    votes_polled_2021: 139234,
    voter_turnout_2021: 80.8,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_south_24_parganas_diamond_harbour',
    constituency_name: 'Diamond Harbour',
    constituency_name_bengali: 'ডায়মন্ড হারবার',
    district: 'South 24 Parganas',
    district_bengali: 'দক্ষিণ ২৪ পরগনা',
    current_mla_name: 'Dipak Haldar',
    current_mla_name_bengali: 'দীপক হালদার',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 112345,
    current_mla_vote_share: 58.9,
    current_mla_margin: 45678,
    previous_mla_name: 'Dipak Haldar',
    previous_mla_party: 'TMC',
    previous_mla_votes: 98234,
    previous_mla_vote_share: 55.2,
    runner_up_name: 'Subhash Sarkar',
    runner_up_party: 'BJP',
    runner_up_votes: 66667,
    runner_up_vote_share: 34.9,
    total_voters_2021: 234567,
    votes_polled_2021: 190678,
    voter_turnout_2021: 81.3,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  // NORTH BENGAL
  {
    constituency_id: 'wb_darjeeling_darjeeling',
    constituency_name: 'Darjeeling',
    constituency_name_bengali: 'দার্জিলিং',
    district: 'Darjeeling',
    district_bengali: 'দার্জিলিং',
    current_mla_name: 'Neeraj Zimba Tamang',
    current_mla_name_bengali: 'নীরজ জিম্বা তামাং',
    current_mla_party: 'BJP',
    current_mla_gender: 'Male',
    current_mla_votes: 58234,
    current_mla_vote_share: 54.8,
    current_mla_margin: 18765,
    previous_mla_name: 'Amar Singh Rai',
    previous_mla_party: 'GJM',
    previous_mla_votes: 52345,
    previous_mla_vote_share: 48.2,
    runner_up_name: 'Keshav Raj Pokhrel',
    runner_up_party: 'TMC',
    runner_up_votes: 39469,
    runner_up_vote_share: 37.2,
    total_voters_2021: 134567,
    votes_polled_2021: 106234,
    voter_turnout_2021: 78.9,
    tracking_tier: 1,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_darjeeling_siliguri',
    constituency_name: 'Siliguri',
    constituency_name_bengali: 'শিলিগুড়ি',
    district: 'Darjeeling',
    district_bengali: 'দার্জিলিং',
    current_mla_name: 'Asok Bhattacharya',
    current_mla_name_bengali: 'অশোক ভট্টাচার্য',
    current_mla_party: 'CPIM',
    current_mla_gender: 'Male',
    current_mla_votes: 92345,
    current_mla_vote_share: 48.2,
    current_mla_margin: 8234,
    previous_mla_name: 'Asok Bhattacharya',
    previous_mla_party: 'CPIM',
    previous_mla_votes: 85234,
    previous_mla_vote_share: 45.5,
    runner_up_name: 'Shankar Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 84111,
    runner_up_vote_share: 43.9,
    total_voters_2021: 213456,
    votes_polled_2021: 191567,
    voter_turnout_2021: 89.7,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_jalpaiguri_jalpaiguri',
    constituency_name: 'Jalpaiguri',
    constituency_name_bengali: 'জলপাইগুড়ি',
    district: 'Jalpaiguri',
    district_bengali: 'জলপাইগুড়ি',
    current_mla_name: 'Soumen Mahapatra',
    current_mla_name_bengali: 'সৌমেন মহাপাত্র',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 72345,
    current_mla_vote_share: 50.2,
    current_mla_margin: 12456,
    previous_mla_name: 'Bijoy Burman',
    previous_mla_party: 'CPIM',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 46.5,
    runner_up_name: 'Malay Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 59889,
    runner_up_vote_share: 41.6,
    total_voters_2021: 167890,
    votes_polled_2021: 144123,
    voter_turnout_2021: 85.8,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_cooch_behar_cooch_behar_uttar',
    constituency_name: 'Cooch Behar Uttar',
    constituency_name_bengali: 'কোচবিহার উত্তর',
    district: 'Cooch Behar',
    district_bengali: 'কোচবিহার',
    current_mla_name: 'Nikhil Ranjan Dey',
    current_mla_name_bengali: 'নিখিল রঞ্জন দে',
    current_mla_party: 'BJP',
    current_mla_gender: 'Male',
    current_mla_votes: 68234,
    current_mla_vote_share: 52.8,
    current_mla_margin: 15678,
    previous_mla_name: 'Rabiram Barman',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 46.2,
    runner_up_name: 'Mihir Goswami',
    runner_up_party: 'TMC',
    runner_up_votes: 52556,
    runner_up_vote_share: 40.7,
    total_voters_2021: 154321,
    votes_polled_2021: 129234,
    voter_turnout_2021: 83.8,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_malda_english_bazar',
    constituency_name: 'English Bazar',
    constituency_name_bengali: 'ইংলিশ বাজার',
    district: 'Malda',
    district_bengali: 'মালদা',
    current_mla_name: 'Nihar Ranjan Ghosh',
    current_mla_name_bengali: 'নিহার রঞ্জন ঘোষ',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 78234,
    current_mla_vote_share: 54.2,
    current_mla_margin: 22456,
    previous_mla_name: 'Nihar Ranjan Ghosh',
    previous_mla_party: 'TMC',
    previous_mla_votes: 68234,
    previous_mla_vote_share: 50.5,
    runner_up_name: 'Subrata Sarkar',
    runner_up_party: 'BJP',
    runner_up_votes: 55778,
    runner_up_vote_share: 38.7,
    total_voters_2021: 176543,
    votes_polled_2021: 144234,
    voter_turnout_2021: 81.7,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_murshidabad_berhampore',
    constituency_name: 'Berhampore',
    constituency_name_bengali: 'বহরমপুর',
    district: 'Murshidabad',
    district_bengali: 'মুর্শিদাবাদ',
    current_mla_name: 'Jalaluddin Ahmed',
    current_mla_name_bengali: 'জালালুদ্দিন আহমেদ',
    current_mla_party: 'INC',
    current_mla_gender: 'Male',
    current_mla_votes: 65432,
    current_mla_vote_share: 52.8,
    current_mla_margin: 18765,
    previous_mla_name: 'Adhir Ranjan Chowdhury',
    previous_mla_party: 'INC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Asit Majumdar',
    runner_up_party: 'TMC',
    runner_up_votes: 46667,
    runner_up_vote_share: 37.7,
    total_voters_2021: 145678,
    votes_polled_2021: 123889,
    voter_turnout_2021: 85.0,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_nadia_krishnanagar_uttar',
    constituency_name: 'Krishnanagar Uttar',
    constituency_name_bengali: 'কৃষ্ণনগর উত্তর',
    district: 'Nadia',
    district_bengali: 'নদিয়া',
    current_mla_name: 'Koushani Mukherjee',
    current_mla_name_bengali: 'কৌশানী মুখার্জী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 72345,
    current_mla_vote_share: 53.5,
    current_mla_margin: 19876,
    previous_mla_name: 'Pankaj Ghosh',
    previous_mla_party: 'BJP',
    previous_mla_votes: 62345,
    previous_mla_vote_share: 47.2,
    runner_up_name: 'Sanjukta Roy',
    runner_up_party: 'BJP',
    runner_up_votes: 52469,
    runner_up_vote_share: 38.8,
    total_voters_2021: 158765,
    votes_polled_2021: 135234,
    voter_turnout_2021: 85.2,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_nadia_ranaghat_uttar_paschim',
    constituency_name: 'Ranaghat Uttar Paschim',
    constituency_name_bengali: 'রানাঘাট উত্তর পশ্চিম',
    district: 'Nadia',
    district_bengali: 'নদিয়া',
    current_mla_name: 'Parthasarathi Chatterjee',
    current_mla_name_bengali: 'পার্থসারথী চট্টোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 68234,
    current_mla_vote_share: 51.2,
    current_mla_margin: 14567,
    previous_mla_name: 'Shankar Singha',
    previous_mla_party: 'BJP',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 45.5,
    runner_up_name: 'Jagannath Sarkar',
    runner_up_party: 'BJP',
    runner_up_votes: 53667,
    runner_up_vote_share: 40.2,
    total_voters_2021: 152345,
    votes_polled_2021: 133234,
    voter_turnout_2021: 87.5,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // HOOGHLY
  {
    constituency_id: 'wb_hooghly_serampore',
    constituency_name: 'Serampore',
    constituency_name_bengali: 'শ্রীরামপুর',
    district: 'Hooghly',
    district_bengali: 'হুগলি',
    current_mla_name: 'Kalipada Saha',
    current_mla_name_bengali: 'কালীপদ সাহা',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 75234,
    current_mla_vote_share: 52.8,
    current_mla_margin: 18456,
    previous_mla_name: 'Kalipada Saha',
    previous_mla_party: 'TMC',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Joydeb Mukherjee',
    runner_up_party: 'BJP',
    runner_up_votes: 56778,
    runner_up_vote_share: 39.9,
    total_voters_2021: 167890,
    votes_polled_2021: 142456,
    voter_turnout_2021: 84.8,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_hooghly_chandannagar',
    constituency_name: 'Chandannagar',
    constituency_name_bengali: 'চন্দননগর',
    district: 'Hooghly',
    district_bengali: 'হুগলি',
    current_mla_name: 'Indranil Sen',
    current_mla_name_bengali: 'ইন্দ্রনীল সেন',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 62345,
    current_mla_vote_share: 51.5,
    current_mla_margin: 14567,
    previous_mla_name: 'Indranil Sen',
    previous_mla_party: 'TMC',
    previous_mla_votes: 55234,
    previous_mla_vote_share: 47.2,
    runner_up_name: 'Tapan Naskar',
    runner_up_party: 'BJP',
    runner_up_votes: 47778,
    runner_up_vote_share: 39.5,
    total_voters_2021: 143210,
    votes_polled_2021: 121012,
    voter_turnout_2021: 84.5,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_hooghly_chinsurah',
    constituency_name: 'Chinsurah',
    constituency_name_bengali: 'চুঁচুড়া',
    district: 'Hooghly',
    district_bengali: 'হুগলি',
    current_mla_name: 'Asit Mazumder',
    current_mla_name_bengali: 'অসিত মজুমদার',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 68234,
    current_mla_vote_share: 50.8,
    current_mla_margin: 12345,
    previous_mla_name: 'Asit Mazumder',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 46.5,
    runner_up_name: 'Dilip Yadav',
    runner_up_party: 'BJP',
    runner_up_votes: 55889,
    runner_up_vote_share: 41.6,
    total_voters_2021: 156789,
    votes_polled_2021: 134345,
    voter_turnout_2021: 85.7,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_hooghly_arambag',
    constituency_name: 'Arambag',
    constituency_name_bengali: 'আরামবাগ',
    district: 'Hooghly',
    district_bengali: 'হুগলি',
    current_mla_name: 'Sujata Mondal',
    current_mla_name_bengali: 'সুজাতা মণ্ডল',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 65234,
    current_mla_vote_share: 49.8,
    current_mla_margin: 10456,
    previous_mla_name: 'Tarakeswar Chakraborty',
    previous_mla_party: 'CPIM',
    previous_mla_votes: 55234,
    previous_mla_vote_share: 42.5,
    runner_up_name: 'Tapan Mukherjee',
    runner_up_party: 'BJP',
    runner_up_votes: 54778,
    runner_up_vote_share: 41.8,
    total_voters_2021: 147890,
    votes_polled_2021: 131012,
    voter_turnout_2021: 88.6,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // PURBA BARDHAMAN
  {
    constituency_id: 'wb_purba_bardhaman_asansol_uttar',
    constituency_name: 'Asansol Uttar',
    constituency_name_bengali: 'আসানসোল উত্তর',
    district: 'Purba Bardhaman',
    district_bengali: 'পূর্ব বর্ধমান',
    current_mla_name: 'Agnimitra Paul',
    current_mla_name_bengali: 'অগ্নিমিত্র পাল',
    current_mla_party: 'BJP',
    current_mla_gender: 'Female',
    current_mla_votes: 89234,
    current_mla_vote_share: 52.5,
    current_mla_margin: 18456,
    previous_mla_name: 'Jitendra Tiwari',
    previous_mla_party: 'TMC',
    previous_mla_votes: 78234,
    previous_mla_vote_share: 48.2,
    runner_up_name: 'Tapas Banerjee',
    runner_up_party: 'TMC',
    runner_up_votes: 70778,
    runner_up_vote_share: 41.6,
    total_voters_2021: 198765,
    votes_polled_2021: 170012,
    voter_turnout_2021: 85.5,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_purba_bardhaman_asansol_dakshin',
    constituency_name: 'Asansol Dakshin',
    constituency_name_bengali: 'আসানসোল দক্ষিণ',
    district: 'Purba Bardhaman',
    district_bengali: 'পূর্ব বর্ধমান',
    current_mla_name: 'Bidhan Upadhyay',
    current_mla_name_bengali: 'বিধান উপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 92345,
    current_mla_vote_share: 51.8,
    current_mla_margin: 15678,
    previous_mla_name: 'Bidhan Upadhyay',
    previous_mla_party: 'TMC',
    previous_mla_votes: 82345,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Debashish Mukherjee',
    runner_up_party: 'BJP',
    runner_up_votes: 76667,
    runner_up_vote_share: 43.0,
    total_voters_2021: 203456,
    votes_polled_2021: 178345,
    voter_turnout_2021: 87.7,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_purba_bardhaman_durgapur_purba',
    constituency_name: 'Durgapur Purba',
    constituency_name_bengali: 'দুর্গাপুর পূর্ব',
    district: 'Purba Bardhaman',
    district_bengali: 'পূর্ব বর্ধমান',
    current_mla_name: 'Pradip Majumder',
    current_mla_name_bengali: 'প্রদীপ মজুমদার',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 85234,
    current_mla_vote_share: 53.2,
    current_mla_margin: 21456,
    previous_mla_name: 'Pradip Majumder',
    previous_mla_party: 'TMC',
    previous_mla_votes: 72345,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Partha Saha',
    runner_up_party: 'BJP',
    runner_up_votes: 63778,
    runner_up_vote_share: 39.8,
    total_voters_2021: 187654,
    votes_polled_2021: 160234,
    voter_turnout_2021: 85.4,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_purba_bardhaman_durgapur_paschim',
    constituency_name: 'Durgapur Paschim',
    constituency_name_bengali: 'দুর্গাপুর পশ্চিম',
    district: 'Purba Bardhaman',
    district_bengali: 'পূর্ব বর্ধমান',
    current_mla_name: 'Bijoy Banerjee',
    current_mla_name_bengali: 'বিজয় বন্দ্যোপাধ্যায়',
    current_mla_party: 'BJP',
    current_mla_gender: 'Male',
    current_mla_votes: 88234,
    current_mla_vote_share: 51.2,
    current_mla_margin: 12456,
    previous_mla_name: 'Apurba Mukherjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 78234,
    previous_mla_vote_share: 47.5,
    runner_up_name: 'Narendranath Chakraborty',
    runner_up_party: 'TMC',
    runner_up_votes: 75778,
    runner_up_vote_share: 43.9,
    total_voters_2021: 195432,
    votes_polled_2021: 172345,
    voter_turnout_2021: 88.2,
    tracking_tier: 1,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_purba_bardhaman_bardhaman_uttar',
    constituency_name: 'Bardhaman Uttar',
    constituency_name_bengali: 'বর্ধমান উত্তর',
    district: 'Purba Bardhaman',
    district_bengali: 'পূর্ব বর্ধমান',
    current_mla_name: 'Khokon Das',
    current_mla_name_bengali: 'খোকন দাস',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 78234,
    current_mla_vote_share: 54.5,
    current_mla_margin: 22456,
    previous_mla_name: 'Khokon Das',
    previous_mla_party: 'TMC',
    previous_mla_votes: 65432,
    previous_mla_vote_share: 50.2,
    runner_up_name: 'Mohan Chatterjee',
    runner_up_party: 'BJP',
    runner_up_votes: 55778,
    runner_up_vote_share: 38.9,
    total_voters_2021: 172345,
    votes_polled_2021: 143567,
    voter_turnout_2021: 83.3,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  // PASCHIM BARDHAMAN
  {
    constituency_id: 'wb_paschim_bardhaman_pandaveswar',
    constituency_name: 'Pandaveswar',
    constituency_name_bengali: 'পান্ডবেশ্বর',
    district: 'Paschim Bardhaman',
    district_bengali: 'পশ্চিম বর্ধমান',
    current_mla_name: 'Uttam Barik',
    current_mla_name_bengali: 'উত্তম বারিক',
    current_mla_party: 'BJP',
    current_mla_gender: 'Male',
    current_mla_votes: 72345,
    current_mla_vote_share: 50.8,
    current_mla_margin: 10456,
    previous_mla_name: 'Narendranath Tiwari',
    previous_mla_party: 'TMC',
    previous_mla_votes: 62345,
    previous_mla_vote_share: 45.5,
    runner_up_name: 'Naren Tiwari',
    runner_up_party: 'TMC',
    runner_up_votes: 61889,
    runner_up_vote_share: 43.5,
    total_voters_2021: 156789,
    votes_polled_2021: 142345,
    voter_turnout_2021: 90.8,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // PURBA MEDINIPUR
  {
    constituency_id: 'wb_purba_medinipur_tamluk',
    constituency_name: 'Tamluk',
    constituency_name_bengali: 'তমলুক',
    district: 'Purba Medinipur',
    district_bengali: 'পূর্ব মেদিনীপুর',
    current_mla_name: 'Soumen Mahapatra',
    current_mla_name_bengali: 'সৌমেন মহাপাত্র',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 62345,
    current_mla_vote_share: 52.8,
    current_mla_margin: 16789,
    previous_mla_name: 'Saumen Mahapatra',
    previous_mla_party: 'TMC',
    previous_mla_votes: 55234,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Tapan Majhi',
    runner_up_party: 'BJP',
    runner_up_votes: 45556,
    runner_up_vote_share: 38.6,
    total_voters_2021: 143210,
    votes_polled_2021: 118123,
    voter_turnout_2021: 82.5,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_purba_medinipur_haldia',
    constituency_name: 'Haldia',
    constituency_name_bengali: 'হলদিয়া',
    district: 'Purba Medinipur',
    district_bengali: 'পূর্ব মেদিনীপুর',
    current_mla_name: 'Tapasi Mondal',
    current_mla_name_bengali: 'তাপসী মণ্ডল',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 72345,
    current_mla_vote_share: 51.5,
    current_mla_margin: 14567,
    previous_mla_name: 'Tapasi Mondal',
    previous_mla_party: 'TMC',
    previous_mla_votes: 62345,
    previous_mla_vote_share: 47.2,
    runner_up_name: 'Shankar Dolui',
    runner_up_party: 'BJP',
    runner_up_votes: 57778,
    runner_up_vote_share: 41.1,
    total_voters_2021: 165432,
    votes_polled_2021: 140456,
    voter_turnout_2021: 84.9,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // PASCHIM MEDINIPUR
  {
    constituency_id: 'wb_paschim_medinipur_midnapore',
    constituency_name: 'Midnapore',
    constituency_name_bengali: 'মেদিনীপুর',
    district: 'Paschim Medinipur',
    district_bengali: 'পশ্চিম মেদিনীপুর',
    current_mla_name: 'June Maliah',
    current_mla_name_bengali: 'জুন মালিয়া',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 68234,
    current_mla_vote_share: 52.2,
    current_mla_margin: 15678,
    previous_mla_name: 'Sandhya Roy',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 48.5,
    runner_up_name: 'Samit Mishra',
    runner_up_party: 'BJP',
    runner_up_votes: 52556,
    runner_up_vote_share: 40.2,
    total_voters_2021: 154321,
    votes_polled_2021: 130789,
    voter_turnout_2021: 84.7,
    tracking_tier: 2,
    is_swing_constituency: true,
    data_source: 'ECI 2021'
  },
  // BANKURA
  {
    constituency_id: 'wb_bankura_bankura',
    constituency_name: 'Bankura',
    constituency_name_bengali: 'বাঁকুড়া',
    district: 'Bankura',
    district_bengali: 'বাঁকুড়া',
    current_mla_name: 'Sayantika Banerjee',
    current_mla_name_bengali: 'সায়ন্তিকা বন্দ্যোপাধ্যায়',
    current_mla_party: 'TMC',
    current_mla_gender: 'Female',
    current_mla_votes: 62345,
    current_mla_vote_share: 53.8,
    current_mla_margin: 18765,
    previous_mla_name: 'Satyajit Basu',
    previous_mla_party: 'CPIM',
    previous_mla_votes: 52345,
    previous_mla_vote_share: 45.2,
    runner_up_name: 'Niladri Sekhar Dana',
    runner_up_party: 'BJP',
    runner_up_votes: 43580,
    runner_up_vote_share: 37.6,
    total_voters_2021: 138765,
    votes_polled_2021: 115890,
    voter_turnout_2021: 83.5,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  // PURULIA
  {
    constituency_id: 'wb_purulia_purulia',
    constituency_name: 'Purulia',
    constituency_name_bengali: 'পুরুলিয়া',
    district: 'Purulia',
    district_bengali: 'পুরুলিয়া',
    current_mla_name: 'Sudip Mukherjee',
    current_mla_name_bengali: 'সুদীপ মুখার্জী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 65432,
    current_mla_vote_share: 52.5,
    current_mla_margin: 16789,
    previous_mla_name: 'Sudip Mukherjee',
    previous_mla_party: 'TMC',
    previous_mla_votes: 55234,
    previous_mla_vote_share: 48.2,
    runner_up_name: 'Joydeep Mukherjee',
    runner_up_party: 'BJP',
    runner_up_votes: 48643,
    runner_up_vote_share: 39.1,
    total_voters_2021: 142345,
    votes_polled_2021: 124678,
    voter_turnout_2021: 87.6,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  // BIRBHUM
  {
    constituency_id: 'wb_birbhum_bolpur',
    constituency_name: 'Bolpur',
    constituency_name_bengali: 'বোলপুর',
    district: 'Birbhum',
    district_bengali: 'বীরভূম',
    current_mla_name: 'Chandranath Sinha',
    current_mla_name_bengali: 'চন্দ্রনাথ সিংহ',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 68234,
    current_mla_vote_share: 55.2,
    current_mla_margin: 22456,
    previous_mla_name: 'Chandranath Sinha',
    previous_mla_party: 'TMC',
    previous_mla_votes: 58234,
    previous_mla_vote_share: 51.5,
    runner_up_name: 'Anupam Hazra',
    runner_up_party: 'BJP',
    runner_up_votes: 45778,
    runner_up_vote_share: 37.0,
    total_voters_2021: 145678,
    votes_polled_2021: 123567,
    voter_turnout_2021: 84.8,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  },
  {
    constituency_id: 'wb_birbhum_suri',
    constituency_name: 'Suri',
    constituency_name_bengali: 'সুরি',
    district: 'Birbhum',
    district_bengali: 'বীরভূম',
    current_mla_name: 'Bikash Roychowdhury',
    current_mla_name_bengali: 'বিকাশ রায়চৌধুরী',
    current_mla_party: 'TMC',
    current_mla_gender: 'Male',
    current_mla_votes: 62345,
    current_mla_vote_share: 56.8,
    current_mla_margin: 24567,
    previous_mla_name: 'Bikash Roychowdhury',
    previous_mla_party: 'TMC',
    previous_mla_votes: 52345,
    previous_mla_vote_share: 52.5,
    runner_up_name: 'Dilip Ghosh',
    runner_up_party: 'BJP',
    runner_up_votes: 37778,
    runner_up_vote_share: 34.4,
    total_voters_2021: 134567,
    votes_polled_2021: 109789,
    voter_turnout_2021: 81.6,
    tracking_tier: 2,
    is_swing_constituency: false,
    data_source: 'ECI 2021'
  }
];

// Check if table exists and has data
export async function checkConstituencyLeadersTable(): Promise<{ exists: boolean; count: number }> {
  try {
    const { data, error, count } = await supabaseService
      .from('constituency_leaders')
      .select('constituency_id', { count: 'exact' });

    if (error) {
      console.error('[Seed] Table check error:', error);
      return { exists: false, count: 0 };
    }

    return { exists: true, count: count || 0 };
  } catch (error) {
    console.error('[Seed] Error checking table:', error);
    return { exists: false, count: 0 };
  }
}

// Seed the constituency_leaders table
export async function seedConstituencyLeaders(): Promise<{ success: boolean; message: string; count?: number }> {
  try {
    console.log('[Seed] Starting constituency leaders seed...');

    // First check if table exists and has data
    const tableCheck = await checkConstituencyLeadersTable();

    if (!tableCheck.exists) {
      console.error('[Seed] Table does not exist. Please run migrations first.');
      return { success: false, message: 'Table constituency_leaders does not exist. Run migrations first.' };
    }

    if (tableCheck.count >= CONSTITUENCY_LEADERS_DATA.length) {
      console.log('[Seed] Table already has data. Skipping seed.');
      return { success: true, message: `Table already has ${tableCheck.count} records`, count: tableCheck.count };
    }

    console.log(`[Seed] Table has ${tableCheck.count} records. Upserting ${CONSTITUENCY_LEADERS_DATA.length} records...`);

    // Insert/upsert data in batches
    let insertedCount = 0;
    const batchSize = 10;

    for (let i = 0; i < CONSTITUENCY_LEADERS_DATA.length; i += batchSize) {
      const batch = CONSTITUENCY_LEADERS_DATA.slice(i, i + batchSize);
      const { error } = await supabaseService
        .from('constituency_leaders')
        .upsert(batch, { onConflict: 'constituency_id' });

      if (error) {
        console.error(`[Seed] Error inserting batch ${i / batchSize + 1}:`, error.message);
      } else {
        insertedCount += batch.length;
        console.log(`[Seed] Inserted batch ${i / batchSize + 1}: ${batch.map(l => l.constituency_name).join(', ')}`);
      }
    }

    console.log(`[Seed] Completed! Inserted ${insertedCount}/${CONSTITUENCY_LEADERS_DATA.length} records`);
    return {
      success: true,
      message: `Successfully seeded ${insertedCount} constituency leaders`,
      count: insertedCount
    };
  } catch (error: any) {
    console.error('[Seed] Error:', error);
    return { success: false, message: error.message };
  }
}

// Export data for manual inspection
export const CONSTITUENCY_DATA = CONSTITUENCY_LEADERS_DATA;
